project:
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "LANDFIRE training"
  navbar:
    search: TRUE
    pinned: true
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: source

